name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag'
        required: true
        type: string

permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: read
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Github actions have Node and Yarn already set-up by default
    # It is not clear which versions these are, 
    # so it might be a good idea to specify them via an action like actions/setup-node@v4
    - uses: actions/checkout@v4
    - name: tag commit
      env:
        TAG: ${{ github.event.inputs.version }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        git config user.name "github-bot"
        git config user.email "github-bot@noreply.com"
        git tag -a "${TAG}" -m "Release ${TAG}"
        git push origin "refs/tags/${TAG}"
    - name: Install
      run: yarn
    - name: Unit tests
      run: yarn test
    - name: Build
      run: yarn build
    - name: Integration tests
      run: yarn test:e2e
    - name: publishing Test results
      uses: EnricoMi/publish-unit-test-result-action@v2.20.0
      if: always()
      with: 
        files: "**/reports/**/*.xml"
