name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        type
  
permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: read
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Github actions have Node and Yarn already set-up by default
    # It is not clear which versions these are, 
    # so it might be a good idea to specify them via an action like actions/setup-node@v4
    - uses: actions/checkout@v4
    - name: Install
      run: yarn
    - name: Unit tests
      run: yarn test
    - name: Build
      run: yarn build
    - name: Integration tests
      run: yarn test:e2e
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ input.version }}
        release_name: Release ${{ input.version }}
        draft: false
        prerelease: false
    - name: Collect test reports
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: 'reports/*.xml'
